# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: cfcompile
      uses: foundeo/cfml-compiler-action@master
      with:
        cfengine: lucee@5.2.9.31
      #uses: docker://foundeo/cfml-ci-tools:latest
      #with: 
      #  entrypoint: /opt/box/box
      #  args: cfcompile sourcePath=/github/workspace destPath=/tmp
    - name: Start Up
      run: docker-compose up &

    - name: Wait for startup 
      run: tests/curl/server-up.sh
    
    - name: Run curl test 
      run: tests/curl/curl.sh
    
    - name: Run Postman Newman Tests
      run: npx newman run tests/newman/ci-example.postman_collection.json
  testbox:
    runs-on: ubuntu-latest
    env:
        LUCEE_EXTENSIONS: "37C61C0A-5D7E-4256-8572639BE0CF5838"
    container:
      image: foundeo/cfml-ci-tools:latest
    steps:  
    - uses: actions/checkout@v2
    - name: Start a server
      run: box server start cfengine=lucee@5.2.9.31
    - name: Install dependencies
      run: box install
    - name: Run TestBox Tests
      run: box testbox run
      
        
